// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: resp_msg.proto

package lib

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RetCode int32

const (
	RetCode_Unknown            RetCode = 0
	RetCode_Ok                 RetCode = 1
	RetCode_Srv                RetCode = 2
	RetCode_Para               RetCode = 3
	RetCode_Register           RetCode = 4
	RetCode_SignIn             RetCode = 5
	RetCode_SignOut            RetCode = 6
	RetCode_SignCheck          RetCode = 7
	RetCode_Exist              RetCode = 8
	RetCode_NotExist           RetCode = 9
	RetCode_UpdateErr          RetCode = 10
	RetCode_Occupied           RetCode = 11
	RetCode_DeletionNotAllowed RetCode = 12
	RetCode_StatusErr          RetCode = 13
	RetCode_Max                RetCode = 100 // 最大号段
)

// Enum value maps for RetCode.
var (
	RetCode_name = map[int32]string{
		0:   "Unknown",
		1:   "Ok",
		2:   "Srv",
		3:   "Para",
		4:   "Register",
		5:   "SignIn",
		6:   "SignOut",
		7:   "SignCheck",
		8:   "Exist",
		9:   "NotExist",
		10:  "UpdateErr",
		11:  "Occupied",
		12:  "DeletionNotAllowed",
		13:  "StatusErr",
		100: "Max",
	}
	RetCode_value = map[string]int32{
		"Unknown":            0,
		"Ok":                 1,
		"Srv":                2,
		"Para":               3,
		"Register":           4,
		"SignIn":             5,
		"SignOut":            6,
		"SignCheck":          7,
		"Exist":              8,
		"NotExist":           9,
		"UpdateErr":          10,
		"Occupied":           11,
		"DeletionNotAllowed": 12,
		"StatusErr":          13,
		"Max":                100,
	}
)

func (x RetCode) Enum() *RetCode {
	p := new(RetCode)
	*p = x
	return p
}

func (x RetCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RetCode) Descriptor() protoreflect.EnumDescriptor {
	return file_resp_msg_proto_enumTypes[0].Descriptor()
}

func (RetCode) Type() protoreflect.EnumType {
	return &file_resp_msg_proto_enumTypes[0]
}

func (x RetCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RetCode.Descriptor instead.
func (RetCode) EnumDescriptor() ([]byte, []int) {
	return file_resp_msg_proto_rawDescGZIP(), []int{0}
}

type RespMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Error code
	Ret RetCode `protobuf:"varint,1,opt,name=ret,proto3,enum=pb_resp.RetCode" json:"ret,omitempty"`
	// Error message
	// @inject_tag: json:"msg"
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"msg"`
	// Error detail
	Detail string `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
}

func (x *RespMessage) Reset() {
	*x = RespMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_resp_msg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespMessage) ProtoMessage() {}

func (x *RespMessage) ProtoReflect() protoreflect.Message {
	mi := &file_resp_msg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespMessage.ProtoReflect.Descriptor instead.
func (*RespMessage) Descriptor() ([]byte, []int) {
	return file_resp_msg_proto_rawDescGZIP(), []int{0}
}

func (x *RespMessage) GetRet() RetCode {
	if x != nil {
		return x.Ret
	}
	return RetCode_Unknown
}

func (x *RespMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RespMessage) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

var File_resp_msg_proto protoreflect.FileDescriptor

var file_resp_msg_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x72, 0x65, 0x73, 0x70, 0x5f, 0x6d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x07, 0x70, 0x62, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x22, 0x63, 0x0a, 0x0b, 0x52, 0x65, 0x73,
	0x70, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x22, 0x0a, 0x03, 0x72, 0x65, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x70, 0x62, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x2e,
	0x52, 0x65, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x03, 0x72, 0x65, 0x74, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x2a, 0xcd,
	0x01, 0x0a, 0x07, 0x52, 0x65, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x6e,
	0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x6b, 0x10, 0x01, 0x12,
	0x07, 0x0a, 0x03, 0x53, 0x72, 0x76, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x50, 0x61, 0x72, 0x61,
	0x10, 0x03, 0x12, 0x0c, 0x0a, 0x08, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x10, 0x04,
	0x12, 0x0a, 0x0a, 0x06, 0x53, 0x69, 0x67, 0x6e, 0x49, 0x6e, 0x10, 0x05, 0x12, 0x0b, 0x0a, 0x07,
	0x53, 0x69, 0x67, 0x6e, 0x4f, 0x75, 0x74, 0x10, 0x06, 0x12, 0x0d, 0x0a, 0x09, 0x53, 0x69, 0x67,
	0x6e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x10, 0x07, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x78, 0x69, 0x73,
	0x74, 0x10, 0x08, 0x12, 0x0c, 0x0a, 0x08, 0x4e, 0x6f, 0x74, 0x45, 0x78, 0x69, 0x73, 0x74, 0x10,
	0x09, 0x12, 0x0d, 0x0a, 0x09, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x45, 0x72, 0x72, 0x10, 0x0a,
	0x12, 0x0c, 0x0a, 0x08, 0x4f, 0x63, 0x63, 0x75, 0x70, 0x69, 0x65, 0x64, 0x10, 0x0b, 0x12, 0x16,
	0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x6f, 0x74, 0x41, 0x6c, 0x6c,
	0x6f, 0x77, 0x65, 0x64, 0x10, 0x0c, 0x12, 0x0d, 0x0a, 0x09, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x45, 0x72, 0x72, 0x10, 0x0d, 0x12, 0x07, 0x0a, 0x03, 0x4d, 0x61, 0x78, 0x10, 0x64, 0x42, 0x3b,
	0x5a, 0x39, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x67, 0x65,
	0x6e, 0x74, 0x2d, 0x63, 0x68, 0x61, 0x74, 0x65, 0x65, 0x2f, 0x61, 0x69, 0x2e, 0x63, 0x68, 0x61,
	0x74, 0x65, 0x65, 0x2d, 0x67, 0x6f, 0x2d, 0x61, 0x70, 0x69, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x2f,
	0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x62, 0x2f, 0x6c, 0x69, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_resp_msg_proto_rawDescOnce sync.Once
	file_resp_msg_proto_rawDescData = file_resp_msg_proto_rawDesc
)

func file_resp_msg_proto_rawDescGZIP() []byte {
	file_resp_msg_proto_rawDescOnce.Do(func() {
		file_resp_msg_proto_rawDescData = protoimpl.X.CompressGZIP(file_resp_msg_proto_rawDescData)
	})
	return file_resp_msg_proto_rawDescData
}

var file_resp_msg_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_resp_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_resp_msg_proto_goTypes = []interface{}{
	(RetCode)(0),        // 0: pb_resp.RetCode
	(*RespMessage)(nil), // 1: pb_resp.RespMessage
}
var file_resp_msg_proto_depIdxs = []int32{
	0, // 0: pb_resp.RespMessage.ret:type_name -> pb_resp.RetCode
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_resp_msg_proto_init() }
func file_resp_msg_proto_init() {
	if File_resp_msg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_resp_msg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_resp_msg_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_resp_msg_proto_goTypes,
		DependencyIndexes: file_resp_msg_proto_depIdxs,
		EnumInfos:         file_resp_msg_proto_enumTypes,
		MessageInfos:      file_resp_msg_proto_msgTypes,
	}.Build()
	File_resp_msg_proto = out.File
	file_resp_msg_proto_rawDesc = nil
	file_resp_msg_proto_goTypes = nil
	file_resp_msg_proto_depIdxs = nil
}
